(load "utilities.lisp")
(load "henley.lisp")
(load "shakespeare.lisp")

(defun main ()
	(format t "FILENAME: ")
	(let ((filename (read-line)))
    (format t "HOW MANY STANZAS WILL YOU REQUIRE? ")
    (let ((stanzas (parse-integer (read-line))))
      (format t "AND THE LINES PER STANZA? ")
      (let ((lines-per (parse-integer (read-line))))
        ;(format t "Filename: ~A~%" filename)
        ;(format t "Stanzas: ~A~%" stanzas)
        ;(format t "Lines per stanza: ~A~%" lines-per)
        (format t "THE POEM... ~%~%")
        (read-text filename)
        (will-meets-walt stanzas lines-per)))))

(main)